hosts:
  webservers:
    hosts:
      web1:
        ansible_host: 192.168.1.10
        ansible_user: user1
      web2:
        ansible_host: 192.168.1.11
        ansible_user: user2
  database:
    hosts:
      db1:
        ansible_host: 192.168.1.20
        ansible_user: user3
      db2:
        ansible_host: 192.168.1.21
        ansible_user: user4