- name: Restart web server
  service:
    name: apache2
    state: restarted
  when: ansible_os_family == "Debian"

- name: Restart web server
  service:
    name: httpd
    state: restarted
  when: ansible_os_family == "RedHat"