- hosts: all
  become: yes
  tasks:
    - name: Update all packages to the latest version
      apt:
        upgrade: dist
        update_cache: yes

    - name: Clean up unused packages
      apt:
        autoremove: yes
        purge: yes